/**
 * Content der Content-Pages und Legal-Pages (extrahiert aus den bestehenden
 * page.tsx-Files). Kommt als Text-Block in die pages-Collection.
 */

import type { Block } from "./lib/lexical";

export type PageContent = {
  path: string;
  contentBlocks: Block[];
  faqs?: Array<{ question: string; answer: string }>;
};

export const pageContent: PageContent[] = [
  {
    path: "/impressum/",
    contentBlocks: [
      { type: "p", text: "PB Fahrzeugpflege" },
      { type: "p", text: "Provinzialstraße 243" },
      { type: "p", text: "66806 Ensdorf" },
      { type: "p", text: "Telefon: +49 6898 1905" },
      { type: "p", text: "Fax: +49 6898 1906" },
      { type: "p", text: "E-Mail: kontakt@pb-fahrzeugpflege.de" },
      { type: "p", text: "Webseite: www.pb-fahrzeugpflege.de" },
      { type: "p", text: "Inhaber: Thomas Paul" },
      { type: "p", text: "USt-IdNr.: DE309394124" },
      { type: "h2", text: "Haftung für Inhalte" },
      { type: "p", text: "Wir sind gemäß § 7 Absatz 1 TMG für eigene Inhalte auf diesen Seiten verantwortlich. Nach den §§ 8 bis 10 TMG sind wir jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben davon unberührt. Eine Haftung ist erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entfernen wir entsprechende Inhalte umgehend." },
      { type: "h2", text: "Haftung für Links" },
      { type: "p", text: "Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber verantwortlich. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen entfernen wir derartige Links umgehend." },
      { type: "h2", text: "Urheberrecht" },
      { type: "p", text: "Die durch uns erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Inhalte Dritter werden als solche gekennzeichnet. Sollten Sie dennoch eine Urheberrechtsverletzung bemerken, bitten wir um einen Hinweis. Bei Bekanntwerden entfernen wir entsprechende Inhalte umgehend." },
      { type: "h2", text: "Datenschutz" },
      { type: "p", text: "Unsere Datenschutzerklärung finden Sie unter /datenschutzerklaerung/." },
      { type: "h2", text: "EU-Streitschlichtung" },
      { type: "p", text: "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr/. Unsere E-Mail-Adresse finden Sie oben im Impressum." },
      { type: "h2", text: "Verbraucherstreitbeilegung / Universalschlichtungsstelle" },
      { type: "p", text: "Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen." },
    ],
  },
  {
    path: "/datenschutzerklaerung/",
    contentBlocks: [
      { type: "h2", text: "Verantwortliche Stelle" },
      { type: "p", text: "PB Fahrzeugpflege, Inhaber: Thomas Paul, Provinzialstraße 243, 66806 Ensdorf, Telefon: +49 6898 1905, E-Mail: kontakt@pb-fahrzeugpflege.de" },
      { type: "h2", text: "Allgemeine Hinweise zur Datenverarbeitung" },
      { type: "p", text: "Wir verarbeiten personenbezogene Daten ausschließlich im Einklang mit der Datenschutzgrundverordnung sowie den geltenden nationalen Datenschutzgesetzen. Die Nutzung unserer Website ist grundsätzlich ohne Angabe personenbezogener Daten möglich. Personenbezogene Daten werden nur verarbeitet, soweit dies zur Bereitstellung einer funktionsfähigen Website oder zur Bearbeitung Ihrer Anfrage erforderlich ist." },
      { type: "h2", text: "Hosting (Vercel)" },
      { type: "p", text: "Diese Website wird bei Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, USA (bzw. deren Rechenzentren in der EU) gehostet. Beim Aufruf der Website werden technisch notwendige Daten (u. a. IP-Adresse, Browsertyp, Uhrzeit) in Server-Log-Dateien verarbeitet. Rechtsgrundlage ist Artikel 6 Absatz 1 Buchstabe f DSGVO (berechtigtes Interesse an sicherem und effizientem Website-Betrieb). Es besteht ein Auftragsverarbeitungsvertrag nach Artikel 28 DSGVO." },
      { type: "h2", text: "Server-Log-Dateien" },
      { type: "p", text: "Beim Besuch unserer Website werden automatisch Daten erfasst, die Ihr Browser übermittelt. Dazu zählen Browsertyp und -version, verwendetes Betriebssystem, Referrer-URL, Hostname des zugreifenden Rechners, Uhrzeit der Serveranfrage und IP-Adresse. Diese Daten sind technisch notwendig, um die Website anzuzeigen und die Stabilität zu gewährleisten. Eine Zusammenführung dieser Daten mit anderen Datenquellen findet nicht statt." },
      { type: "h2", text: "Cookies und Einwilligungsverwaltung" },
      { type: "p", text: "Unsere Website verwendet Cookies. Grundlage hierfür ist das Consent-Management-System CookieYes (CookieYes Limited, 3 Warren Yard, Warren Farm Office Village, Milton Keynes, England). Nutzer können selbst bestimmen, in welche Kategorien sie einwilligen möchten. Technisch notwendige Cookies werden ohne Einwilligung gesetzt, da sie für den Betrieb der Website erforderlich sind. Alle anderen Cookies werden nur nach ausdrücklicher Zustimmung aktiviert. Ihre Cookie-Einstellungen können jederzeit über die CookieYes-Oberfläche angepasst werden." },
      { type: "h2", text: "Google Tag Manager" },
      { type: "p", text: "Wir nutzen Google Tag Manager der Google Ireland Limited, um Marketing- und Analyse-Tags zentral zu verwalten. Der Tag Manager selbst erhebt keine personenbezogenen Daten, führt aber Tags aus, die dies tun können. Die dadurch geladenen Dienste werden nur nach vorheriger Einwilligung über CookieYes aktiv. Rechtsgrundlage für die Einbindung ist Artikel 6 Absatz 1 Buchstabe f DSGVO (berechtigtes Interesse an effizienter Tag-Verwaltung)." },
      { type: "h2", text: "Kontaktformular und Formsubmit" },
      { type: "p", text: "Wenn Sie unser Kontaktformular nutzen, verarbeiten wir die von Ihnen eingegebenen Daten (Vorname, E-Mail-Adresse, optional Telefonnummer und Fahrzeugangaben, Nachricht). Der technische Versand der Formularanfrage erfolgt über den Dienst Formsubmit (Formsubmit, USA). Formsubmit dient dabei als reiner Übermittlungs-Dienstleister: Die Anfrage wird von unserem Server an Formsubmit übertragen und von dort per E-Mail an kontakt@pb-fahrzeugpflege.de weitergeleitet. Formsubmit speichert die Formularinhalte für die Weiterleitung kurzzeitig zwischen; eine dauerhafte Speicherung erfolgt bei Formsubmit nach unserem Kenntnisstand nicht." },
      { type: "p", text: "Die Verarbeitung Ihrer Anfrage-Inhalte erfolgt auf Grundlage von Artikel 6 Absatz 1 Buchstabe b DSGVO (vorvertragliche Maßnahmen bzw. Vertragsdurchführung) bzw. Buchstabe f DSGVO (berechtigtes Interesse an der Beantwortung Ihrer Anfrage). Die Daten werden nach abgeschlossener Bearbeitung gelöscht, sofern keine gesetzlichen Aufbewahrungspflichten entgegenstehen. Da Formsubmit in den USA sitzt, kann eine Übermittlung in ein Drittland stattfinden; für einen Nicht-EU-Empfang gelten die Anforderungen des Kapitel V DSGVO." },
      { type: "p", text: "Zum Schutz vor Spam nutzen wir zusätzlich ein Honeypot-Feld (technisch unsichtbar, für Menschen nicht ausfüllbar) sowie ein Rate-Limit (maximal 5 Anfragen pro Stunde pro IP-Adresse)." },
      { type: "h2", text: "Terminbuchung via Calendly" },
      { type: "p", text: "Auf unserer Kontaktseite binden wir das Terminbuchungs-Widget von Calendly (Calendly LLC, 271 17th Street NW, Suite 1000, Atlanta, GA 30363, USA) ein. Beim Aufruf der Seite wird eine Verbindung zu Calendly-Servern aufgebaut, wobei technische Daten wie IP-Adresse, Browsertyp und aufgerufene Seiten übertragen werden können. Bei einer Terminbuchung übermitteln Sie zusätzlich Name, E-Mail und optionale Angaben direkt an Calendly. Rechtsgrundlage: Artikel 6 Absatz 1 Buchstabe b DSGVO (vorvertragliche Maßnahmen) bzw. f DSGVO (berechtigtes Interesse an effizienter Terminvereinbarung). Da Calendly in den USA sitzt, findet eine Drittstaaten-Übermittlung statt." },
      { type: "h2", text: "Google Maps Embed" },
      { type: "p", text: "Auf unserer Startseite betten wir eine Google-Maps-Karte zur Darstellung unseres Standorts ein. Anbieter ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Beim Laden der Karte wird eine Verbindung zu Google-Servern aufgebaut und Ihre IP-Adresse an Google übertragen. Diese kann von Google in den USA verarbeitet werden. Rechtsgrundlage ist Artikel 6 Absatz 1 Buchstabe f DSGVO (berechtigtes Interesse an einer leicht auffindbaren Standortdarstellung)." },
      { type: "h2", text: "WhatsApp-Button" },
      { type: "p", text: "Der WhatsApp-Button führt direkt zu einer Kommunikation über WhatsApp. Durch das Öffnen des Buttons werden Daten an WhatsApp übertragen. Verantwortlicher Dienstanbieter ist WhatsApp Ireland Ltd., 4 Grand Canal Square, Dublin 2, Irland. Bitte beachten Sie, dass WhatsApp unter Umständen Nutzerdaten an Meta-Unternehmen weitergibt. Die Nutzung erfolgt freiwillig. Wir raten dazu, über WhatsApp keine sensiblen Informationen zu versenden." },
      { type: "h2", text: "ProvenExpert-Widget" },
      { type: "p", text: "Wir binden auf unserer Seite ein Widget des Bewertungsdienstleisters ProvenExpert (Expert Systems AG, Quedlinburger Straße 1, 10589 Berlin) ein. Beim Aufruf der Seiten mit Widget wird eine Verbindung zu ProvenExpert-Servern aufgebaut, wobei technische Daten wie Ihre IP-Adresse übertragen werden können. Rechtsgrundlage: Artikel 6 Absatz 1 Buchstabe f DSGVO (berechtigtes Interesse an der Darstellung unserer Kundenbewertungen)." },
      { type: "h2", text: "werkenntdenBESTEN-Siegel" },
      { type: "p", text: "Wir zeigen ein Kunden-Empfehlungssiegel von werkenntdenBESTEN (mediarocket GmbH). Beim Laden des Siegels wird eine Verbindung zu deren Servern aufgebaut. Rechtsgrundlage: Artikel 6 Absatz 1 Buchstabe f DSGVO (berechtigtes Interesse an der Darstellung unserer Bewertungen)." },
      { type: "h2", text: "Weitergabe von Daten" },
      { type: "p", text: "Eine Weitergabe personenbezogener Daten erfolgt nur, wenn dies zur Vertragserfüllung notwendig ist, eine gesetzliche Verpflichtung besteht oder Sie ausdrücklich eingewilligt haben. Eine Weitergabe zu Werbezwecken findet nicht statt." },
      { type: "h2", text: "Speicherdauer" },
      { type: "p", text: "Personenbezogene Daten werden nur so lange gespeichert, wie es für die jeweiligen Zwecke erforderlich ist. Gesetzliche Aufbewahrungsfristen bleiben unberührt." },
      { type: "h2", text: "Sicherheit" },
      { type: "p", text: "Wir treffen technische und organisatorische Maßnahmen, um Ihre Daten gegen Verlust, Missbrauch oder unbefugten Zugriff zu schützen. Diese Maßnahmen entsprechen dem aktuellen Stand der Technik." },
      { type: "h2", text: "Ihre Rechte" },
      { type: "p", text: "Sie haben folgende Rechte: Auskunft über gespeicherte Daten · Berichtigung unrichtiger Daten · Löschung Ihrer Daten · Einschränkung der Verarbeitung · Widerspruch gegen die Verarbeitung · Datenübertragbarkeit · Beschwerderecht bei einer Datenschutzaufsichtsbehörde." },
      { type: "h2", text: "Aktualität dieser Erklärung" },
      { type: "p", text: "Diese Datenschutzerklärung wird regelmäßig aktualisiert. Es gilt stets die aktuelle Fassung auf dieser Seite." },
    ],
  },
  {
    path: "/allgemeine-geschaeftsbedingungen/",
    contentBlocks: [
      { type: "h2", text: "1. Geltungsbereich" },
      { type: "p", text: "Diese AGB gelten für alle Dienstleistungen und Warenlieferungen der PB Fahrzeugpflege, Provinzialstraße 243, 66806 Ensdorf. Sie gelten für Verbraucher und Unternehmer im Sinne der §§ 13, 14 BGB gleichermaßen." },
      { type: "h2", text: "2. Angebot und Vertragsschluss" },
      { type: "p", text: "Angebote erfolgen grundsätzlich nach Besichtigung des Fahrzeugs und einer individuellen Abstimmung des Leistungsumfangs. Der Vertrag kommt spätestens mit Abgabe des Fahrzeugs zur Durchführung der Arbeiten zustande. Terminvereinbarungen gelten als verbindliche Reservierung des Arbeitszeitraums." },
      { type: "h2", text: "3. Kostenvoranschläge" },
      { type: "p", text: "Kostenvoranschläge sind unverbindlich. Für Kostenvoranschläge kann eine Gebühr in Höhe von bis zu 15 Prozent des voraussichtlichen Auftragswertes berechnet werden. Voraussetzung ist, dass der Kunde vor Erstellung des Kostenvoranschlags ausdrücklich auf die Kosten hingewiesen wurde und dem zugestimmt hat. Die Zustimmung kann mündlich, schriftlich oder in Textform (z. B. E-Mail, WhatsApp) erfolgen. Die Gebühr wird bei Auftragserteilung vollständig auf den Endpreis angerechnet." },
      { type: "p", text: "Lehnt der Kunde den Auftrag nach Erstellung des Kostenvoranschlags ab, verbleibt die Gebühr als Vergütung für den erbrachten Aufwand." },
      { type: "h2", text: "4. Terminvergabe, Absagefristen, Ausfallentschädigung, Anzahlungen" },
      { type: "p", text: "Termine sind verbindlich. Viele unserer Leistungen erfordern umfangreiche Vorbereitungen und können kurzfristig nicht neu vergeben werden. Eine Absage oder Terminverschiebung ist daher bis spätestens 72 Stunden vor dem vereinbarten Termin kostenfrei möglich." },
      { type: "p", text: "Erfolgt eine Absage weniger als 72 Stunden vorher oder erscheint der Kunde nicht, behalten wir uns vor, eine angemessene Ausfallentschädigung in Höhe von bis zu 80 Prozent des vereinbarten oder geschätzten Auftragswertes zu berechnen. Dies gilt insbesondere, wenn reservierte Arbeitszeit, Werkflächen, Vorbereitung oder eingeplantes Personal kurzfristig nicht mehr anderweitig genutzt werden können. Dem Kunden bleibt der Nachweis vorbehalten, dass kein oder ein geringerer Schaden entstanden ist." },
      { type: "p", text: "Für bestimmte Leistungen, insbesondere Keramikversiegelungen sowie zeitintensive oder mehrtägige Aufbereitungen, kann eine Anzahlung verlangt werden. Die Anzahlung stellt eine Abschlagszahlung auf den späteren Gesamtpreis dar und wird vollständig auf die Endrechnung angerechnet. Wird ein solcher Termin weniger als 72 Stunden vorher abgesagt oder erscheint der Kunde nicht, verfällt die geleistete Anzahlung als Teil der Ausfallentschädigung. Ist der tatsächliche Schaden höher als die Anzahlung, können zusätzlich bis zu 80 Prozent des Auftragswertes berechnet werden, soweit dies den entstandenen Ausfall abbildet." },
      { type: "p", text: "Absagen oder Terminänderungen, die außerhalb unserer Geschäftszeiten eingehen, gelten erst mit Beginn des nächsten Werktages als zugegangen. Nachrichten auf dem Anrufbeantworter, per E-Mail, WhatsApp oder anderen Messengern werden erst mit tatsächlicher Kenntnisnahme während unserer regulären Öffnungszeiten wirksam. Absagen am Wochenende, an Feiertagen oder spät abends gelten daher frühestens ab dem folgenden Werktag als eingegangen. Die 72-Stunden-Frist wird ab diesem Zeitpunkt berechnet." },
      { type: "h2", text: "5. Zahlungsbedingungen" },
      { type: "p", text: "Die Zahlung erfolgt ausschließlich vor Ort in bar oder per EC-Karte. Zahlungen auf Rechnung sind nicht möglich. Die Vergütung ist mit Abschluss der Arbeiten sofort fällig." },
      { type: "h2", text: "6. Durchführung der Arbeiten / Übergabe" },
      { type: "p", text: "Das Fahrzeug muss zum vereinbarten Termin zugänglich übergeben werden und vollständig leergeräumt sein. Für Schäden oder Verluste an im Fahrzeug zurückgelassenen Gegenständen übernehmen wir keine Haftung, sofern diese nicht auf Vorsatz oder grober Fahrlässigkeit unsererseits beruhen. Mängel oder Vorschäden sind bei Fahrzeugabgabe mitzuteilen. Nach Fertigstellung erfolgt die Abnahme vor Ort. Spätere Reklamationen, die bei üblicher Sorgfalt bei Abnahme erkennbar gewesen wären, können nicht berücksichtigt werden." },
      { type: "h2", text: "7. Keramikversiegelung: Schutzdauer, Pflegepflicht & Haftung" },
      { type: "p", text: "Die Haltbarkeit unserer Keramikversiegelungen beträgt bis zu 3 Jahre, bei entsprechender Pflege noch deutlich länger. Dies ist jedoch stark von regelmäßiger und sachgemäßer Pflege abhängig. Wir übernehmen keine Garantie für die Haltbarkeit. Der Kunde ist verpflichtet, unsere Pflegehinweise einzuhalten. Eine unsachgemäße Pflege kann zu frühzeitigem Versagen der Versiegelung führen. Eine Nachbesserung erfolgt nur nach Kulanz und Einzelfallprüfung." },
      { type: "h2", text: "8. Haftung bei Lackzuständen, Vorschäden und Altarbeiten" },
      { type: "p", text: "Viele Fahrzeuge weisen bei Übergabe Vorschäden, verdeckte Mängel oder zuvor instandgesetzte Bereiche auf. Diese sind häufig ohne Demontage, Spezialwerkzeuge oder tiefere Reinigung nicht erkennbar. Im Zuge unserer fachgerechten Arbeiten, beispielsweise bei Politur, Lackkorrektur, Reinigung oder Versiegelung, können solche Altzustände sichtbar werden oder sich verstärken. Dies beruht ausschließlich auf dem bestehenden Zustand des Fahrzeugs und stellt keinen Mangel unserer Leistung dar." },
      { type: "p", text: "Gleiches gilt für altersbedingt instabile, gealterte oder vorgeschädigte Bauteile wie Clips, Halterungen, Zierleisten, Befestigungen, Kunststoffe oder Klebestellen, die aufgrund von Materialermüdung, Vorreparaturen, Spannungsrissen oder unsachgemäßen Vorarbeiten empfindlich reagieren oder versagen können. Lösen sich solche Bauteile, brechen sie oder treten weitere optische Veränderungen auf, liegt dies regelmäßig in den bestehenden Vorschäden oder Materialschwächen begründet." },
      { type: "p", text: "Wir übernehmen keine Haftung für Schäden, Ablösungen, sichtbare Übergänge, Farbveränderungen, Materialbrüche oder andere Folgeerscheinungen, die durch solche Altzustände, Vorschäden, Materialermüdung oder nicht fachgerecht ausgeführte Vorarbeiten verursacht werden, soweit dies gesetzlich zulässig ist." },
      { type: "p", text: "Der Kunde ist verpflichtet, bei Auftragserteilung bekannte Vorschäden oder frühere Reparaturen mitzuteilen. Eine Haftung für verdeckte Vorschäden besteht nur im Rahmen der gesetzlichen Bestimmungen." },
      { type: "h2", text: "9. Versicherungsaufträge & Fremdaufträge" },
      { type: "p", text: "Bei Aufträgen im Namen oder im Auftrag Dritter, zum Beispiel durch Versicherungen, Gutachter, Leasinggeber oder sonstige Institutionen, haftet der jeweilige Auftraggeber für die Richtigkeit und Vollständigkeit der übermittelten Angaben. Wir übernehmen keine Verantwortung für fehlerhafte oder unvollständige Vorgaben Dritter." },
      { type: "p", text: "Unsere Einschätzungen, Bewertungen oder Stellungnahmen zu Schäden, Zuständen oder Reparaturmöglichkeiten ersetzen kein Gutachten und basieren ausschließlich auf dem sichtbaren Zustand zum Zeitpunkt der Begutachtung. Verdeckte Mängel oder Schäden, die ohne Demontage, Spezialwerkzeuge oder weitergehende Prüfverfahren nicht erkennbar sind, fallen nicht in unsere Haftung." },
      { type: "p", text: "Jegliche Kostenschätzungen oder Einschätzungen zu Reparaturmaßnahmen erfolgen nach bestem Wissen und auf Grundlage unserer Erfahrung. Eine Haftung für Abweichungen oder spätere Feststellungen besteht nur im Rahmen der gesetzlichen Bestimmungen." },
      { type: "h2", text: "10. Datenschutz / Videoüberwachung" },
      { type: "p", text: "Zum Schutz unserer Kunden und Mitarbeiter sind unsere Räumlichkeiten kameraüberwacht. Dies ist durch deutliche Hinweisschilder vor Ort kenntlich gemacht. Die Aufzeichnung dient ausschließlich internen Sicherheits- und Dokumentationszwecken. Eine Verwendung zur Beweisführung bei Auftragsstreitigkeiten behalten wir uns vor. Daten werden DSGVO-konform verarbeitet und nach maximal 7 Tagen automatisch gelöscht, sofern sie nicht aus berechtigtem Grund länger gespeichert werden müssen (z. B. bei Rechtsstreitigkeiten)." },
      { type: "h2", text: "11. Gerichtsstand / Schlussbestimmungen" },
      { type: "p", text: "Es gilt deutsches Recht. Gerichtsstand ist Saarlouis, sofern der Kunde Kaufmann ist. Sollte eine Bestimmung dieser AGB unwirksam sein oder werden, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt." },
    ],
  },
  {
    path: "/ueber-uns/",
    contentBlocks: [
      { type: "h2", text: "Im Jahr 1997 …" },
      { type: "p", text: "… als junge und ambitionierte Unternehmer im Alter von 18 und 24 Jahren, haben wir – Thomas Paul und Karsten Becker – die professionelle Fahrzeugaufbereitung im Saarland auf ein neues Level gehoben. Während andere sich auf die Massenabfertigung für Autohäuser und Gebrauchtwagenhändler konzentrierten, hatten wir ein anderes Ziel:" },
      { type: "p", text: "Wir wollten der beste Fahrzeugaufbereiter im Saarland werden, mit einem klaren Fokus auf den Privatkunden." },
      { type: "p", text: "Unsere Leidenschaft für Perfektion und unser unermüdlicher Ehrgeiz haben uns zum Erfolg geführt. Fast drei Jahrzehnte später haben wir nicht nur unser Ziel erreicht, sondern weit übertroffen. Heute dürfen wir Kunden aus ganz Deutschland und sogar darüber hinaus bei PB Fahrzeugpflege Saarlouis® begrüßen. Unsere Liebe zum Detail und unser Engagement für höchste Qualität haben uns zu einer festen Größe in der Branche gemacht." },
      { type: "h2", text: "Erfahrung, die Vertrauen schafft" },
      { type: "p", text: "In den vergangenen Jahrzehnten haben wir nicht nur unser Handwerk perfektioniert, sondern auch ein tiefes Verständnis für die Bedürfnisse unserer Kunden entwickelt. Unsere Geschichte ist geprägt von stetiger Weiterentwicklung und der Fähigkeit, uns immer wieder neu zu erfinden, um den hohen Ansprüchen unserer Kunden gerecht zu werden." },
      { type: "h2", text: "Warum PB Fahrzeugpflege Saarlouis®?" },
      { type: "p", text: "Unsere Expertise und unser kompromissloser Qualitätsanspruch machen uns zur ersten Wahl, wenn es um die professionelle Fahrzeugaufbereitung geht. Ob es um eine gründliche Reinigung, eine Lackkorrektur oder eine hochmoderne Keramikversiegelung geht – bei PB Fahrzeugpflege Saarlouis® erhalten Sie Ergebnisse, die Ihren Erwartungen nicht nur gerecht werden, sondern sie übertreffen." },
      { type: "p", text: "Wir sehen nicht nur Autos, sondern Werte. Jedes Fahrzeug ist für uns ein Unikat und bekommt eine maßgeschneiderte Behandlung." },
      { type: "p", text: "Bei uns gibt's keine leeren Versprechungen aus Hochglanzprospekten, sondern 100 % ehrliche Handwerkskunst mit Ergebnissen, die dauerhaft überzeugen." },
      { type: "p", text: "Wenn Sie Wert auf Qualität legen, wenn für Sie Klasse statt Kompromisse zählt, dann sind wir für Sie genau die Richtigen." },
    ],
  },
  {
    path: "/preise/",
    contentBlocks: [
      { type: "p", text: "Worum geht es bei Ihrem Fahrzeug?" },
      { type: "h2", text: "Leasingrückgabe – Kosten vermeiden" },
      { type: "p", text: "Wir sorgen dafür, dass Ihr Fahrzeug so übergeben wird, dass unnötige Nachzahlungen an den Leasinggeber vermieden werden. Gründlich, zielgerichtet und ohne Überraschungen." },
      { type: "h2", text: "Fahrzeugverkauf – Wert steigern" },
      { type: "p", text: "Ein aufbereitetes Fahrzeug verkauft sich schneller und zu besseren Konditionen. Wir holen optisch und technisch das Maximum heraus, damit Ihr Wagen den bestmöglichen Eindruck hinterlässt." },
      { type: "h2", text: "Sammlerfahrzeug – Wert erhalten" },
      { type: "p", text: "Hier geht es nicht um den schnellen Glanz, sondern um langfristigen Werterhalt. Mit Fingerspitzengefühl und Erfahrung schützen wir, was Ihnen wichtig ist – über Jahre hinweg." },
      { type: "h2", text: "Lack- & Beulendoktor-Arbeiten – Präzision statt Flickwerk" },
      { type: "p", text: "Ob kleine Dellen oder Lackschäden: Unser Anspruch ist, dass Sie nachher nichts mehr sehen. Präzise, sauber und fachgerecht – ohne billige Kompromisse. Mehr erfahren." },
      { type: "h2", text: "Keramikversiegelung – Schutz & Perfektion" },
      { type: "p", text: "Die Königsklasse unserer Arbeit: Ein mehrstufiger Prozess, der für maximalen Schutz, langanhaltenden Glanz und ein perfektes Finish sorgt. Kein Produkt von der Stange, sondern Handwerk auf höchstem Niveau. Mehr erfahren." },
      { type: "p", text: "Sicher verstehen Sie jetzt, warum bei uns jeder Auftrag mit einer Analyse beginnt. Wir sehen uns Ihr Fahrzeug im Detail an, sprechen über Ihre Ziele und sagen offen, was wirklich sinnvoll ist – und was nicht." },
      { type: "p", text: "Um es klar zu sagen: Jahrzehntelange Erfahrung, durchdachte Abläufe, hochwertigste Materialien und vor allem Zeit gibt es nicht zum Billigpreis. Ja, es gibt günstigere Anbieter – die meisten sogar. Doch wer nur nach dem niedrigsten Preis sucht, bekommt selten den höchsten Wert." },
      { type: "p", text: "Wir stehen für Qualität statt Kompromisse. Für eine klare Linie. Für Ergebnisse, die überzeugen – unabhängig davon, welches Ziel Sie mit Ihrem Fahrzeug verfolgen. Darum geben wir keine Pauschalpreise am Telefon oder per Mail." },
      { type: "p", text: "Wenn all das für Sie logisch klingt, sind Sie bei uns richtig. Kommen Sie ohne Termin vorbei – lassen Sie uns Ihr Fahrzeug gemeinsam ansehen. So entsteht ein individuelles Angebot, das zu Ihrem Fahrzeug und Ihrem Ziel passt. Denn bei uns beginnt Premium schon bei der Beratung." },
      { type: "h2", text: "Orientierungswerte" },
      { type: "p", text: "Damit Sie einen groben Rahmen haben – bitte beachten Sie: Das verbindliche Angebot erstellen wir immer erst nach der persönlichen Begutachtung." },
      { type: "table",
        header: ["Leistung", "Preis", "Hinweis"],
        rows: [
          ["Keramikversiegelung", "1.500 – 1.900 €", "Orientierungswert je nach Fahrzeug und Zustand"],
          ["Leihwagen", "ab 55 € / Tag", "Nach Verfügbarkeit, bitte vorab reservieren"],
          ["Smart Repair", "bis zu 70 % günstiger", "Verglichen mit klassischer Lackierung"],
        ]},
    ],
  },
  {
    path: "/unfallschaden/",
    contentBlocks: [
      { type: "p", text: "Nach einem unverschuldeten Unfall im Saarland übernehmen wir für Sie die komplette Schadenabwicklung und die fachgerechte Reparatur Ihres Fahrzeugs. Bei einem Autounfall geht es nicht nur um einen Schaden, sondern um Kontrolle, um Ihr Recht und um den tatsächlichen Wert Ihres Fahrzeugs. Genau dabei unterstützen wir Sie." },
      { type: "h2", text: "Unfall gehabt? Bleiben Sie entspannt – wir sind für Sie da!" },
      { type: "p", text: "Bei einem Autounfall geht es nicht nur um einen Schaden. Es geht um Kontrolle, um Ihr Recht und um den tatsächlichen Wert Ihres Fahrzeugs. Vielleicht fragen Sie sich gerade:" },
      { type: "ul", items: [
        "Wer zahlt das alles?",
        "Versucht die Versicherung mich abzuzocken?",
        "Muss ich in eine Partnerwerkstatt oder habe ich freie Werkstattwahl?",
        "Was ist mit einer evtl. Wertminderung?",
        "Wie lange bin ich ohne Fahrzeug?",
      ]},
      { type: "h3", text: "Was jetzt Ihre Aufgabe ist" },
      { type: "ul", items: [
        "Erste Hilfe / Polizei (falls erforderlich)",
        "Unfallstelle absichern",
        "Beweisfotos von der Unfallstelle (wichtig wegen Schuldfrage/Zeugen)",
        "Datenaustausch (Personalausweis zeigen lassen, Versicherungsnummer, Kennzeichen)",
      ]},
      { type: "h3", text: "…den kompletten Rest übernehmen wir kostenlos* für Sie" },
      { type: "ul", items: [
        "Unabhängiger Gutachter",
        "Fachanwalt für Verkehrsrecht",
        "Leihfahrzeug",
        "Kommunikation mit der gegnerischen Versicherung",
        "Karosserieinstandsetzung / Lackierung nach Herstellervorgaben",
        "Dokumentation für Wiederverkauf oder Leasingrückgabe",
        "Nur ein Ansprechpartner für alles",
      ]},
      { type: "p", text: "* kostenlos für Sie bei Haftpflichtschäden" },
      { type: "h2", text: "Sie sprechen mit uns – wir sprechen mit allen anderen." },
      { type: "p", text: "Sie erhalten eine klare Einschätzung. Was sinnvoll ist. Was wirtschaftlich ist. Und was Sie besser nicht akzeptieren sollten." },
      { type: "p", text: "Keine Werkstattkette. Keine Schnellabfertigung. Keine Kompromisse auf Kosten des Fahrzeugwertes." },
      { type: "h2", text: "Besonders wichtig bei hochwertigen Fahrzeugen" },
      { type: "p", text: "Bei Premium- und Sportfahrzeugen entscheidet die Qualität der Instandsetzung direkt über den Marktwert. Diese Faktoren bleiben im Fahrzeug – und kommen spätestens beim Verkauf oder bei der Leasingrückgabe ans Licht:" },
      { type: "ul", items: [
        "Unsachgemäße Reparaturen",
        "Falsche Lackschichtstärken",
        "Fehlende Dokumentation",
        "Unprofessionelle Smart-Repair-Lösungen",
      ]},
      { type: "p", text: "Gerade bei höherwertigen Fahrzeugen ist die merkantile Wertminderung ein ernstes Thema. Hier geht es nicht um ein paar Euro. Hier geht es um Substanz. Wer hier billig repariert, zahlt später doppelt." },
      { type: "h2", text: "Versicherungswerkstatt oder eigene Entscheidung?" },
      { type: "p", text: "Viele Versicherer versuchen, Sie in die „Partnerwerkstatt“ zu bekommen. Das geht dann „schnell, standardisiert, kosteneffizient“. Hört sich gut an, ist aber für Sie die denkbar schlechteste Lösung." },
      { type: "p", text: "Denn: Die Versicherung denkt in Schadenssummen. Wir denken in Werterhalt." },
      { type: "p", text: "Sie haben das Recht auf eine fachgerechte Reparatur. Und das Recht auf unabhängige Unterstützung. Nutzen Sie es." },
      { type: "h2", text: "Wer zahlt nach einem Unfall?" },
      { type: "p", text: "Bei einem unverschuldeten Unfall trägt in der Regel die Haftpflichtversicherung des Unfallverursachers die Kosten – darunter die Reparatur, ein unabhängiges Gutachten, ein Ersatzfahrzeug und in vielen Fällen auch einen Anwalt. Für Sie ist unsere Unterstützung in diesen Fällen daher kostenlos. Im Zweifel prüfen wir Ihren Fall unverbindlich, bevor Sie etwas unterschreiben." },
      { type: "h2", text: "Unfallinstandsetzung & Karosseriearbeiten im Saarland" },
      { type: "p", text: "Wir setzen Ihr Fahrzeug nach einem Unfall fachgerecht und nach Herstellervorgaben instand – von der Karosserieinstandsetzung über die Lackierung bis zur Dokumentation für Wiederverkauf oder Leasingrückgabe. Dank unseres Netzwerks aus Karosseriebauern, Lackierern und unabhängigen Gutachtern erhalten Sie alles aus einer Hand." },
      { type: "p", text: "Sie finden uns in der Provinzialstraße 243 in 66806 Ensdorf – direkt bei Saarlouis. Wir sind für Kunden aus dem gesamten Saarland da, u. a. aus Saarlouis, Saarbrücken, Dillingen und St. Wendel, sowie aus dem grenznahen Raum. Eine unverbindliche Begutachtung ist auch ohne Termin möglich – senden Sie uns gern vorab ein Foto per WhatsApp oder über unser Formular." },
    ],
    faqs: [
      { question: "Was tun nach einem Autounfall?", answer: "Sichern Sie zuerst die Unfallstelle, leisten Sie bei Bedarf Erste Hilfe und rufen Sie die Polizei, machen Sie Beweisfotos und tauschen Sie die Daten mit dem Unfallgegner aus (Versicherungsnummer, Kennzeichen). Die weitere Abwicklung übernehmen wir für Sie." },
      { question: "Wer zahlt nach einem Unfall?", answer: "Bei einem unverschuldeten Unfall trägt in der Regel die Haftpflichtversicherung des Unfallverursachers die Kosten – Reparatur, Gutachten, Ersatzfahrzeug und häufig auch den Anwalt. Für Sie ist unsere Unterstützung in diesen Fällen kostenlos." },
      { question: "Muss ich in die Partnerwerkstatt der Versicherung?", answer: "Nein. Bei einem unverschuldeten Unfall müssen Sie sich nicht in die Partnerwerkstatt schicken lassen – Sie entscheiden selbst, wer Ihr Fahrzeug repariert." },
      { question: "Habe ich freie Werkstattwahl?", answer: "Ja. Bei einem unverschuldeten Unfall haben Sie das Recht auf freie Werkstattwahl und auf eine fachgerechte, unabhängige Reparatur." },
      { question: "Was ist eine merkantile Wertminderung?", answer: "Das ist der Wertverlust, den ein Fahrzeug trotz fachgerechter Reparatur allein dadurch erleidet, dass es als Unfallfahrzeug gilt. Gerade bei hochwertigen Fahrzeugen kann dieser Betrag erheblich sein." },
      { question: "Ist ein Parkschaden ein Unfallschaden?", answer: "Grundsätzlich ja: Ein Parkschaden zählt als Unfallschaden, da er durch ein äußeres Ereignis entstanden ist. Ob und wie er reguliert wird, hängt vom Einzelfall und der Schuldfrage ab – wir prüfen das gern unverbindlich für Sie." },
    ],
  },
  {
    path: "/referenzen/",
    contentBlocks: [
      { type: "h2", text: "Zertifikate & Qualitätssiegel" },
      { type: "h3", text: "Q-Siegel" },
      { type: "p", text: "Deutschlands erster Fahrzeugpflege-Betrieb mit Q-Siegel" },
      { type: "p", text: "Auszeichnung durch Minister Heiko Maas. Zweite Auszeichnung in Folge durch Ministerin Anke Rehlinger." },
      { type: "h3", text: "BRILA Certified Installer" },
      { type: "p", text: "Zertifizierter Fachbetrieb für Keramikversiegelungen" },
      { type: "p", text: "BRILA-Urkunde für professionelle Anwendung des 9H High-End-Lackschutzes." },
      { type: "h3", text: "SQD Stufe I" },
      { type: "p", text: "ServiceQualität Deutschland – Stufe I" },
      { type: "p", text: "Zertifikat für nachhaltige Qualitätssicherung im Betrieb seit 2016." },
      { type: "h3", text: "29 Jahre inhabergeführt" },
      { type: "p", text: "Jubiläum 2026" },
      { type: "p", text: "Von zwei jungen Unternehmern zu einem der dienstältesten Fahrzeugpfleger Deutschlands." },
      { type: "h2", text: "ProvenExpert-Auszeichnungen" },
      { type: "p", text: "Jahr für Jahr ausgezeichnet – die Übersicht:" },
      { type: "table",
        header: ["Jahr", "Auszeichnungen"],
        rows: [
          ["2017", "TOP Dienstleister, TOP Empfehlung, TOP Kundenempfehlung"],
          ["2018", "TOP Dienstleister, TOP Empfehlung"],
          ["2019", "TOP Dienstleister, TOP Empfehlung, Von Kunden empfohlen"],
          ["2020", "TOP Dienstleister, TOP Empfehlung"],
          ["2021", "TOP Dienstleister, TOP Empfehlung"],
          ["2022", "TOP Dienstleister"],
          ["2023", "TOP Dienstleister"],
          ["2024", "TOP Dienstleister"],
          ["2026", "ProvenExpert Bewertungssiegel"],
        ]},
      { type: "h2", text: "Weitere Siegel" },
      { type: "p", text: "WerKenntDenBesten Badge – Kunden-Empfehlungssiegel · Kennst du einen? Gold-Bewertung für PB Fahrzeugpflege · Profi-Badge für PB Fahrzeugpflege Saarlouis · TopService-Badge für PB Fahrzeugpflege" },
      { type: "h2", text: "Jubiläen & Presse" },
      { type: "ul", items: [
        "20. Jubiläum – Gratulation durch Ensdorfer Bürgermeister Hartwin Faust",
        "25. Jubiläum – Gratulation vom Ensdorfer Bürgermeister",
        "ZDF – Fernsehteam der Sendung „Drehscheibe“, Thema „Ein Tag Aushilfe als Fahrzeugpfleger“",
        "SR3 Radio (Saarlandwelle) – Fahrzeug-Beschriftung / Karosseriearbeiten",
        "IHK Saar Wirtschaft 10/15 – Pressebericht über die Q-Siegel-Auszeichnung",
        "KITT und Herbie zu Besuch bei PB Fahrzeugpflege Saarlouis",
      ]},
    ],
  },
  {
    path: "/faq/",
    contentBlocks: [
      { type: "p", text: "Hier findest du die häufigsten Fragen rund um Keramikversiegelung und Fahrzeugaufbereitung. Die Antworten sind bewusst klar und praxisnah, ohne Showversprechen. Wenn du es genau wissen willst, komm kurz ohne Termin vorbei oder ruf uns an." },
    ],
    faqs: [
      { question: "Was kostet eine Keramikversiegelung am Auto?", answer: "Als Orientierung liegt eine Keramikversiegelung meist zwischen 1.500 und 1.900 EUR. Entscheidend sind Lackzustand, nötige Lackkorrektur, Größe des Fahrzeugs und der gewünschte Umfang, zum Beispiel Felgen oder Scheiben. Wir machen erst eine kurze Begutachtung und sagen dir dann transparent, was sinnvoll ist. Pauschalpreise ohne diese Angaben sind schlicht unseriös." },
      { question: "Wie lange hält eine Keramikversiegelung wirklich?", answer: "Die Schutzwirkung liegt in der Regel bei etwa 3 Jahren. Wie gut die Optik über die Zeit bleibt, hängt stark von Pflege und Waschmethode ab. Wer regelmäßig falsch wäscht oder aggressive Chemie nutzt, kann die Oberfläche schneller stumpf wirken lassen. Wir erklären dir nach der Abholung kurz, was du tun und lassen solltest." },
      { question: "Wie läuft eine Keramikversiegelung bei Ihnen ab?", answer: "Wir prüfen zuerst den Lackzustand und klären, welches Ergebnis realistisch ist. Danach folgt die gründliche Reinigung, Dekontamination und je nach Zustand die Lackkorrektur. Erst wenn der Lack wirklich sauber vorbereitet ist, wird die Keramik aufgetragen. Am Ende zählt nicht die Keramik, sondern die Vorbereitung, weil dort die Qualität entsteht." },
      { question: "Kann ich mit Keramikversiegelung in die Waschanlage?", answer: "Technisch ja, aber es ist nicht die beste Lösung, wenn du den Lack dauerhaft sauber halten willst. Bürstenanlagen erzeugen auf Dauer Waschkratzer, Keramik verhindert das nicht komplett. Wenn Waschanlage, dann möglichst schonend, und du solltest wissen, dass dunkle Lacke solche Spuren schneller zeigen. Besser ist eine passende Handwäsche oder eine wirklich gute Textilwaschanlage mit sauberer Vorwäsche." },
      { question: "Wie pflege ich ein Auto mit Keramikversiegelung?", answer: "Schonend waschen, keine Bürsten, keine aggressiven Reiniger ohne Grund. Regelmäßige Wäsche mit saurem Autoshampoo erhält Glanz und Abperlen deutlich länger. Wir geben dir nach der Abholung klare Pflegehinweise, damit das Ergebnis im Alltag so bleibt, wie du es abholst." },
      { question: "Wie schnell sollte ein Neuwagen versiegelt werden?", answer: "So früh wie möglich. Viele Neuwagen sind im Rohzustand, also ohne echten Lackschutz, und sammeln schnell die ersten Spuren durch Wäsche, Insekten, Staub und Standzeit. Wer früh versiegelt, hält den Lack länger in einem sauberen Zustand. Je länger du wartest, desto höher ist meistens der Korrekturaufwand." },
      { question: "Wie lange dauert eine Aufbereitung oder Keramikversiegelung?", answer: "Das hängt vom Paket und vom Zustand ab. Eine Außenaufbereitung mit Lackkorrektur wie auch die Innenraumaufbereitung (Trocknung) liegt meist bei 2 Tagen. Eine Keramikversiegelung mit Vorbereitung dauert in der Regel 2 bis 4 Tage. Nach der Begutachtung nennen wir dir eine realistische Dauer." },
      { question: "Wird mein Fahrzeug danach wie neu?", answer: "Manchmal sehr nah dran, aber nicht immer. Tiefe Kratzer, Lackschäden oder bereits nachlackierte Bereiche setzen Grenzen. Unser Anspruch ist ein sichtbar besseres Ergebnis ohne Blender-Versprechen. Bei der Begutachtung zeigen wir dir, was möglich ist und wo man fairerweise Grenzen anerkennen muss." },
      { question: "Warum ist eine Begutachtung vor Ort so wichtig?", answer: "Weil Licht, Fotos und Winkel täuschen. Lackhärte, Kratzerbild, Vorarbeiten, Fahrzeuggröße und Details wie Felgen oder Klavierlack im Innenraum bestimmen den Aufwand. Erst wenn wir das Fahrzeug live sehen, können wir Preis, Dauer und Ergebnis seriös einschätzen." },
      { question: "Muss ich für ein Angebot einen Termin vereinbaren?", answer: "Nein. Du kannst während der Öffnungszeiten ohne Termin vorbeikommen. Wir schauen das Fahrzeug direkt an und klären, was realistisch ist und was nicht. Bei weiterer Anfahrt ist ein kurzer Anruf sinnvoll, damit sicher Zeit für dich ist." },
      { question: "Verfügen Sie über Leihwagen?", answer: "Ja. Ein Leihwagen ist nach Verfügbarkeit möglich. Preis: ab 55 EUR pro Tag. Bitte frühzeitig Bescheid geben, damit wir planen können." },
      { question: "Lohnt sich eine Aufbereitung vor der Leasingrückgabe?", answer: "Sehr oft ja. Viele Rückgaben werden wegen sichtbarer Kleinigkeiten teuer, zum Beispiel matte Lackflächen, Umweltablagerungen, starke Waschkratzer, eingebrannte Insektenreste bzw. Vogelkot oder Innenraumabnutzung und Gerüche. Ebenso werden kleinere Dellen und Abschürfungen am Lack gerne zur Berechnung herangezogen. Durch eine gezielte Aufbereitung können wir die Optik deutlich verbessern und Stress bei der Rückgabe reduzieren. Wir sagen dir vorher ehrlich, was sich rechnet und was nicht." },
      { question: "Neuwagen oder Gebrauchtwagen polieren – wozu überhaupt?", answer: "Ein Neuwagen ist selten wirklich „neu“ im Lack. Transport, Standzeit, Händlerwäsche und schnelle Aufbereitung hinterlassen oft feine Kratzer, Schleier oder Hologramme. Bei Gebrauchtwagen kommen Waschkratzer, Insektenreste, Teer, Flugrost und matte Stellen dazu. Polieren heißt nicht „glänzend machen“, sondern Lackzustand sichtbar verbessern und die Basis für Schutz schaffen. Wenn du Werterhalt willst, führt an einer sauberen Lackkorrektur kaum ein Weg vorbei." },
    ],
  },
];
