/**
 * Service-Detail-Content für den Seed. Extrahiert aus den ursprünglichen
 * hand-designten Detailseiten unter src/app/(frontend)/leistungen/**.
 */

import type { Block } from "./lib/lexical";

export type ServiceDetail = {
  slug: string;
  faqs: Array<{ question: string; answer: string }>;
  contentBlocks: Block[];
};

export const serviceDetails: ServiceDetail[] = [
  {
    slug: "keramikversiegelung",
    faqs: [
      { question: "Was kostet eine Keramikversiegelung?", answer: "Die Kosten richten sich nach Fahrzeuggröße, Lackzustand und Aufbau. Nach einer kurzen Begutachtung erhalten Sie ein transparentes Festpreis-Angebot – unverbindlich und auch ohne Termin. Aktuelle Preise finden Sie auf unserer Seite Preise." },
      { question: "Wie lange hält eine Keramikversiegelung?", answer: "Eine professionell aufgetragene Keramikversiegelung hält in der Regel mehrere Jahre. Die genaue Haltbarkeit hängt von Nutzung und Pflege ab – mit der richtigen Pflege bleibt der Schutz besonders lange erhalten." },
      { question: "Wie lange dauert eine Keramikversiegelung?", answer: "Je nach Fahrzeug und Lackzustand dauert die komplette Aufbereitung und Versiegelung in der Regel zwei bis vier Tage, da wir den Lack vor dem Auftragen gründlich vorbereiten." },
      { question: "Lohnt sich eine Keramikversiegelung beim Neuwagen?", answer: "Ja. Gerade beim Neuwagen ist der Klarlack noch im Rohzustand und besonders empfindlich. Eine Keramikversiegelung ab dem ersten Kilometer schützt den Lack, bevor erste Schäden entstehen, und erhält den Wert des Fahrzeugs." },
      { question: "Keramikversiegelung oder Nanoversiegelung – was ist besser?", answer: "Die Keramikversiegelung ist härter und langlebiger, die Nanoversiegelung günstiger und mit kürzerer Haltbarkeit. Für Neuwagen sowie Sport- und Luxusfahrzeuge empfehlen wir meist die Keramikversiegelung; wir beraten Sie gern individuell." },
      { question: "Eignet sich eine Keramikversiegelung auch für Gebrauchtwagen?", answer: "Ja. Bei Gebrauchtfahrzeugen bereiten wir den Lack vorher auf und entfernen Kratzer und Verunreinigungen, bevor wir die Keramikversiegelung auftragen – ideal zur Werterhaltung." },
      { question: "Schützt eine Keramikversiegelung vor Steinschlag und Kratzern?", answer: "Sie schützt zuverlässig vor Mikrokratzern, UV-Strahlung, Chemie und Verschmutzung. Tiefe Steinschläge kann sie nicht verhindern – dafür ist eine Lackschutzfolie die richtige Wahl. Gern beraten wir Sie zur passenden Lösung." },
      { question: "Kann eine Keramikversiegelung wieder entfernt werden?", answer: "Ja, allerdings nur mechanisch: In unseren internen Tests ließ sich die Versiegelung ausschließlich mit Schleifpaste und Poliermaschine entfernen. Das zeigt, wie widerstandsfähig die Schicht im Alltag ist." },
    ],
    contentBlocks: [
      { type: "p", text: "Eine Keramikversiegelung ist eine glasartige Schutzschicht auf Basis von Siliziumoxid, die sich dauerhaft mit dem Autolack verbindet und ihn vor Umwelteinflüssen, Mikrokratzern und Korrosion schützt. Da wir uns bei PB Fahrzeugpflege Saarlouis höchster Qualität verschrieben haben, dauert eine solche Behandlung nicht selten 2–3 Tage." },
      { type: "p", text: "Der Lack bei Neuwagen befindet sich im absoluten Rohzustand und ist äußeren Einflüssen wie Flugrost, Insektenresten, Baumharz und Mikrokratzern (z. B. durch die Waschanlage) schutzlos ausgesetzt. Gerade in den ersten Kilometern können sich diese Schäden in den noch frischen Klarlack einbrennen. Deshalb ist unsere Keramikversiegelung direkt ab dem ersten Kilometer die beste Wahl, um den Lack langfristig zu schützen." },
      { type: "h2", text: "Warum sollte die Neuwagen-Keramikversiegelung von PB Fahrzeugpflege Saarlouis® durchgeführt werden?" },
      { type: "p", text: "Ihr neues Fahrzeug ist ein Statement, eine Investition und oft ein lang ersehnter Wunsch, der in Erfüllung geht. Doch genau in diesem Neuzustand ist der Lack Ihres Fahrzeugs am empfindlichsten – sozusagen im ungeschützten Rohzustand. Dieser Moment, bevor Ihr Auto den ersten Kilometer auf der Straße zurückgelegt hat, ist der entscheidende Zeitpunkt, um den Lack optimal zu schützen. Und genau hier kommt unsere glasartige Keramikversiegelung für Neuwagen und hochwertige Sportfahrzeuge ins Spiel." },
      { type: "h3", text: "Neuwagen-Lackschutz ab dem ersten Kilometer – weil Perfektion keine Kompromisse kennt" },
      { type: "p", text: "Stellen Sie sich vor, Ihr Fahrzeuglack – unberührt, makellos – trifft auf die raue Realität der Straße: Insekten, Vogelkot, Baumharz, Sahara-Sand, Industriestaub, Blütenstaub, Streusalz, Eis und Schnee. All diese Elemente sind nicht nur störend, sondern können den empfindlichen Lack Ihres Neuwagens in kürzester Zeit angreifen und irreparable Schäden verursachen. Schon wenige Tage können ausreichen, um den Wert und die Ästhetik Ihres Fahrzeugs nachhaltig zu beeinträchtigen." },
      { type: "h3", text: "Vergessen Sie die Märchen – vertrauen Sie auf Expertise" },
      { type: "p", text: "Vielleicht wurde Ihnen beim Kauf gesagt, dass das Autohaus den Lack bereits „versiegelt“ hat. In der Praxis handelt es sich dabei meist nur um eine einfache Wachs- oder Polymerbehandlung – nicht um eine vollwertige Keramikversiegelung. Lassen Sie sich genau erklären, was tatsächlich aufgetragen wurde, bevor Sie auf zusätzlichen Schutz verzichten." },
      { type: "h3", text: "Warum ausgerechnet die PB Fahrzeugpflege Saarlouis Keramikversiegelung?" },
      { type: "p", text: "Unsere Keramikversiegelung bietet weit mehr als nur oberflächlichen Schutz. Sie bildet eine unsichtbare, aber extrem widerstandsfähige Schutzbarriere, die das Eindringen von Schadstoffen verhindert und den Lack Ihres Fahrzeugs langfristig in neuwertigem Zustand erhält. Mit unserer Keramikversiegelung legen Sie den Grundstein für eine Werterhaltung, die dem Anspruch Ihres Neufahrzeugs gerecht wird." },
      { type: "p", text: "Bei PB Fahrzeugpflege Saarlouis® setzen wir auf höchste Präzision, erstklassige Produkte und jahrzehntelange Erfahrung, um Ihnen den besten Schutz für Ihr Fahrzeug zu bieten. Schützen Sie Ihre Investition – von Anfang an. Vertrauen Sie auf die Profis, die wissen, was Ihr Fahrzeug wirklich braucht." },
      { type: "h3", text: "Präzision und Perfektion in jeder Phase" },
      { type: "p", text: "Unsere speziell geschulten Mitarbeiter nehmen sich die Zeit, die Ihr Fahrzeug verdient. In penibler Handarbeit – oft sind dafür mehr als 20 Stunden erforderlich – tragen wir eine hochmoderne, keramische Siliziumoxid-Beschichtung auf den empfindlichen Klarlack Ihres Fahrzeugs auf. Diese glasartige Schicht wirkt wie ein unsichtbarer Schutzpanzer und schützt den Lack Ihres Neuwagens vor den täglichen Herausforderungen, denen er auf der Straße ausgesetzt ist." },
      { type: "h3", text: "Der Schutz, den Ihr Fahrzeug verdient" },
      { type: "p", text: "Die von uns verwendete Keramikversiegelung basiert auf speziellen keramischen Verbindungen, die eine extreme Widerstandsfähigkeit gewährleisten. Diese Versiegelung ist so robust, dass sie in unseren internen Tests nur mit Schleifpaste und Poliermaschine wieder entfernt werden konnte. Das bedeutet, dass Ihr Lack ab sofort besser geschützt ist als je zuvor – gegen alles, was die Umwelt Ihrem Fahrzeug entgegensetzen könnte." },
      { type: "h3", text: "Widerstandsfähigkeit, die sich bewährt hat" },
      { type: "p", text: "Sobald die Keramikversiegelung aufgetragen ist, wird der Lack Ihres Neuwagens deutlich widerstandsfähiger gegenüber Umwelteinflüssen wie UV-Strahlung, Schmutz, Insektenrückständen und vielem mehr. Dieser Schutz ist nicht nur äußerlich sichtbar, sondern bewahrt den Wert und die Ästhetik Ihres Fahrzeugs langfristig." },
      { type: "h3", text: "Warum PB Fahrzeugpflege Saarlouis®?" },
      { type: "p", text: "PB Fahrzeugpflege Saarlouis® gehört zu den dienstältesten Fahrzeugaufbereitungsbetrieben Deutschlands. Als BRILA zertifizierter Fachbetrieb für Keramikversiegelungen (BRILA Certified Installer), Q-Siegel zertifizierter Qualitätsbetrieb und Anbieter mit 187 positiven Kundenbewertungen vertrauen seit 1997 Fahrzeugbesitzer aus dem Saarland, Luxemburg und weit darüber hinaus auf unsere Erfahrung. Unsere Leidenschaft für Perfektion und unser unermüdlicher Einsatz für Qualität machen uns zu den führenden Experten für Keramikversiegelung in Saarlouis, dem Saarland und Luxemburg. Vertrauen Sie uns Ihr Fahrzeug an, und wir sorgen dafür, dass es optimal geschützt und immer in bestmöglichem Zustand bleibt." },
      { type: "blockquote", text: "„Für andere reicht das Erzählte, für uns zählt das Erreichte!“" },
      { type: "p", text: "Sie haben noch weitere Fragen zu unserer Keramikversiegelung? Dann rufen Sie uns einfach an oder kommen Sie einfach ohne Termin zur unverbindlichen Beratung und Angebotserstellung bei uns in Saarlouis / Ensdorf vorbei!" },
      { type: "h2", text: "Was kostet eine Keramikversiegelung?" },
      { type: "p", text: "Die Kosten einer Keramikversiegelung hängen von Fahrzeuggröße, Lackzustand und dem gewünschten Schutzaufbau ab. Da wir jedes Fahrzeug vor der Versiegelung gründlich aufbereiten, erstellen wir Ihnen nach einer kurzen Begutachtung ein transparentes Festpreis-Angebot – unverbindlich und auch ohne Termin. Eine Übersicht finden Sie auf unserer Seite Preise." },
      { type: "h2", text: "Was bringt eine Keramikversiegelung – und für wen lohnt sie sich?" },
      { type: "p", text: "Eine Keramikversiegelung bringt vor allem dreierlei: dauerhaften Schutz vor Umwelteinflüssen, einen intensiven, tiefen Glanz und eine spürbar leichtere Reinigung dank Abperleffekt. Besonders lohnt sie sich bei Fahrzeugen, deren Wert und Erscheinungsbild langfristig erhalten bleiben sollen:" },
      { type: "ul", items: [
        "Neuwagen – Schutz des empfindlichen Klarlacks ab dem ersten Kilometer.",
        "Sport- und Luxusfahrzeuge – kompromissloser Werterhalt und dauerhafter Glanz.",
        "Gebrauchtwagen – nach vorheriger Lackaufbereitung, ideal für hochwertige Fahrzeuge zum Werterhalt.",
      ]},
      { type: "p", text: "Ob sich die Versiegelung für Ihr Fahrzeug lohnt, sagen wir Ihnen ehrlich nach einer kurzen Begutachtung." },
      { type: "h2", text: "Keramik- oder Nanoversiegelung – was ist besser?" },
      { type: "p", text: "Die Keramikversiegelung ist härter und hält deutlich länger, die Nanoversiegelung ist günstiger und schneller aufgetragen. Welche Lösung „besser“ ist, hängt von Anspruch, Budget und Fahrzeug ab – hier die wichtigsten Unterschiede im Überblick:" },
      { type: "table",
        header: ["Kriterium", "Keramikversiegelung", "Nanoversiegelung"],
        rows: [
          ["Haltbarkeit", "Mehrere Jahre", "ca. 12–18 Monate"],
          ["Schutz & Härte", "Sehr hart, glasartig – hoher Schutz", "Guter Schutz, jedoch weicher"],
          ["Glanz & Abperleffekt", "Sehr intensiv", "Gut"],
          ["Aufwand", "Meist 2–3 Tage", "Deutlich geringer"],
          ["Preis", "Höher", "Günstiger"],
          ["Ideal für", "Neuwagen, Sport-, Luxus- & Wertfahrzeuge", "Preisbewusste Pflege mit kürzerer Haltedauer"],
        ]},
      { type: "p", text: "Für Neuwagen, Sport- und Luxusfahrzeuge empfehlen wir in der Regel die Keramikversiegelung. Wer eine günstigere Lösung mit kürzerer Haltedauer sucht, ist mit unserer Nanoversiegelung gut beraten." },
      { type: "h2", text: "Vorteile und Nachteile einer Keramikversiegelung" },
      { type: "p", text: "Eine Keramikversiegelung bietet erhebliche Vorteile, hat aber auch Punkte, die man kennen sollte. Ein ehrlicher Überblick:" },
      { type: "h3", text: "Vorteile" },
      { type: "ul", items: [
        "Langfristiger Lackschutz und Werterhalt",
        "Intensiver Glanz und starker Abperleffekt",
        "Leichtere Reinigung, weniger Anhaftung von Schmutz",
        "Schutz vor UV-Strahlung, Chemie und Mikrokratzern",
      ]},
      { type: "h3", text: "Nachteile / worauf Sie achten sollten" },
      { type: "ul", items: [
        "Höhere Kosten als Wachs oder eine Nanoversiegelung",
        "Aufwendige Anwendung – der Lack muss vorher fachgerecht aufbereitet werden",
        "Kein Schutz vor tiefen Kratzern und Steinschlägen",
        "Regelmäßige Wagenwäsche weiterhin erforderlich",
      ]},
      { type: "p", text: "Genau deshalb führen wir jede Versiegelung in sorgfältiger Handarbeit und nach gründlicher Lackaufbereitung durch." },
    ],
  },
  {
    slug: "nanoversiegelung",
    faqs: [
      { question: "Was kostet eine Nanoversiegelung?", answer: "Die Kosten richten sich nach Fahrzeuggröße und Lackzustand. Als preisbewusste Alternative zur Keramikversiegelung ist die Nanoversiegelung deutlich günstiger. Nach einer kurzen Begutachtung erhalten Sie ein transparentes Angebot – auch ohne Termin. Aktuelle Preise finden Sie auf unserer Seite Preise." },
      { question: "Wie lange hält eine Nanoversiegelung?", answer: "Unsere 1K-Nanoversiegelung bietet langanhaltenden Schutz von bis zu 18 Monaten – deutlich länger als herkömmliches Wachs, das selten über vier Monate hält. Die genaue Standzeit hängt von Nutzung und Pflege ab." },
      { question: "Was ist der Unterschied zwischen Nano- und Keramikversiegelung?", answer: "Die Keramikversiegelung ist härter und hält mehrere Jahre, ist aber teurer und aufwendiger. Die Nanoversiegelung ist die günstigere Lösung mit Schutz bis zu 18 Monaten. Für höchsten, langjährigen Schutz empfehlen wir Keramik; für ein gutes Preis-Leistungs-Verhältnis die Nanoversiegelung." },
      { question: "Was bringt eine Nanoversiegelung beim Auto?", answer: "Sie schützt den Lack vor UV-Strahlung, Streusalz und Umwelteinflüssen, sorgt für intensiven Glanz und einen Abperleffekt, der die Wäsche erleichtert (Easy-to-Clean). Außerdem hält sie deutlich länger als Wachs." },
      { question: "Ist eine Nanoversiegelung sinnvoll?", answer: "Ja, wenn Sie guten Lackschutz zu einem attraktiven Preis möchten. Sie hält deutlich länger als Wachs und lässt sich bei Bedarf später auf eine Keramikversiegelung upgraden." },
      { question: "Nanoversiegelung oder Wachs – was hält länger?", answer: "Die Nanoversiegelung hält klar länger: Während selbst teure Wachse selten über vier Monate halten, schützt unsere 1K-Nanoversiegelung bis zu 18 Monate und verbindet sich fest mit dem Lack, statt nur aufzuliegen." },
      { question: "Hat eine Nanoversiegelung Nachteile?", answer: "Im Vergleich zur Keramikversiegelung ist sie weniger kratzbeständig und muss früher erneuert werden. Dafür ist sie günstiger und schneller aufgetragen – ein sehr gutes Preis-Leistungs-Verhältnis." },
    ],
    contentBlocks: [
      { type: "p", text: "Eine Nanoversiegelung ist eine flüssige Schutzschicht, die sich fest mit dem Autolack verbindet und ihn – einfacher und günstiger als eine Keramikversiegelung – vor Umwelteinflüssen schützt. Bei PB Fahrzeugpflege Saarlouis verwenden wir eine hochwertige 1K-Nanoversiegelung, die bis zu viermal länger hält als eine herkömmliche Wachsversiegelung." },
      { type: "p", text: "Sie ist damit die preisbewusste Alternative zur Keramikversiegelung – für alle, die guten, langanhaltenden Lackschutz zu einem attraktiven Preis möchten." },
      { type: "p", text: "Die von uns verwendete 1K-Nanoversiegelung ist den herkömmlichen Wachsversiegelungen deutlich überlegen. Diese legen sich nur auf die Lackoberfläche und werden durch Autowäsche, Waschanlage und Umwelteinwirkungen schnell wieder abgetragen. Selbst bei den teuersten Wachsen kann eine Standzeit über 4 Monate selten erreicht werden. Ganz anders die von uns verwendete 1K-Nanoversiegelung. Diese verbindet sich fest mit der Lackstruktur und bietet Ihnen einen bisher unerreichten Glanz- und Glättegrad. Der langanhaltende Schutz bis zu 18 Monaten reduziert die Auswirkungen von aggressiven Umwelteinflüssen, UV-Strahlung und Streusalz." },
      { type: "h2", text: "Easy-to-Clean: müheloser Glanz" },
      { type: "p", text: "Dank des Abperleffekts lassen sich Anhaftungen wie Insekten, Vogelkot und Blütenstaub deutlich einfacher entfernen. Diese Easy-to-Clean-Performance sorgt für eine spürbar leichtere Wagenwäsche – Wasser und Schmutz perlen einfach ab." },
      { type: "p", text: "Sie möchten den bestmöglichen Schutz für Ihren Autolack? Dann geht’s hier zu unserer Keramikversiegelung!" },
      { type: "h2", text: "Was kostet eine Nanoversiegelung?" },
      { type: "p", text: "Die Kosten einer Nanoversiegelung hängen von Fahrzeuggröße und Lackzustand ab. Als preisbewusste Alternative zur Keramikversiegelung ist sie deutlich günstiger. Nach einer kurzen Begutachtung erhalten Sie ein transparentes Angebot – unverbindlich und auch ohne Termin. Eine Übersicht finden Sie auf unserer Seite Preise." },
      { type: "h2", text: "Was bringt eine Nanoversiegelung – und ist sie sinnvoll?" },
      { type: "p", text: "Eine Nanoversiegelung schützt den Lack vor UV-Strahlung, Streusalz und Umwelteinflüssen, sorgt für intensiven Glanz und macht dank Abperleffekt die Wäsche leichter. Sinnvoll ist sie vor allem dann, wenn Sie guten, langanhaltenden Lackschutz zu einem attraktiven Preis möchten:" },
      { type: "ul", items: [
        "Alltags- und Gebrauchtfahrzeuge mit gutem Preis-Leistungs-Verhältnis",
        "Als günstiger Einstieg in den professionellen Lackschutz",
        "Wenn ein Schutz für etwa 1–1,5 Jahre statt mehrerer Jahre ausreicht",
      ]},
      { type: "p", text: "Wünschen Sie den höchstmöglichen, langjährigen Schutz, ist unsere Keramikversiegelung die richtige Wahl – wir beraten Sie gern ehrlich." },
      { type: "h2", text: "Nano- oder Keramikversiegelung – was ist besser?" },
      { type: "p", text: "Die Nanoversiegelung ist günstiger und schneller aufgetragen, die Keramikversiegelung härter und langlebiger. Welche Lösung „besser“ ist, hängt von Budget, Anspruch und Fahrzeug ab – hier die wichtigsten Unterschiede im Überblick:" },
      { type: "table",
        header: ["Kriterium", "Nanoversiegelung", "Keramikversiegelung"],
        rows: [
          ["Haltbarkeit", "Bis zu ca. 18 Monate", "Mehrere Jahre"],
          ["Schutz & Härte", "Guter Schutz, flüssig aufgetragen", "Sehr hart, glasartig – höherer Schutz"],
          ["Glanz & Abperleffekt", "Sehr gut (Easy-to-Clean)", "Sehr intensiv"],
          ["Aufwand", "Geringer, schneller aufgetragen", "Sehr hoher Aufwand (2–3 Tage)"],
          ["Preis", "Günstiger", "Höher"],
          ["Ideal für", "Preisbewusste Pflege, gutes Preis-Leistungs-Verhältnis", "Neuwagen, Sport-, Luxus- & Wertfahrzeuge"],
        ]},
      { type: "p", text: "Kurz gesagt: Wer ein gutes Preis-Leistungs-Verhältnis sucht, ist mit der Nanoversiegelung bestens beraten. Für maximalen, langjährigen Schutz empfehlen wir die Keramikversiegelung." },
      { type: "h2", text: "Vorteile und Nachteile einer Nanoversiegelung" },
      { type: "p", text: "Ein ehrlicher Überblick, damit Sie die richtige Wahl treffen:" },
      { type: "h3", text: "Vorteile" },
      { type: "ul", items: [
        "Schutz bis zu 18 Monate – hält bis zu viermal länger als Wachs",
        "Intensiver Glanz und Easy-to-Clean-Effekt",
        "Schutz vor UV-Strahlung, Streusalz und Umwelteinflüssen",
        "Deutlich günstiger als eine Keramikversiegelung",
      ]},
      { type: "h3", text: "Nachteile / worauf Sie achten sollten" },
      { type: "ul", items: [
        "Kürzere Haltbarkeit als eine Keramikversiegelung",
        "Weniger kratzbeständig als eine Keramikbeschichtung",
        "Muss nach einiger Zeit erneuert werden",
      ]},
    ],
  },
  {
    slug: "fahrzeugaufbereitung",
    faqs: [
      { question: "Was kostet eine Fahrzeugaufbereitung?", answer: "Die Kosten richten sich nach Fahrzeuggröße, Zustand und Umfang. Eine reine Innenraumaufbereitung ist günstiger als eine komplette Aufbereitung mit Lackpolitur und Versiegelung. Nach einer kurzen Begutachtung erhalten Sie ein transparentes Angebot – auch ohne Termin. Preise finden Sie auf unserer Seite Preise." },
      { question: "Wie lange dauert eine Fahrzeugaufbereitung?", answer: "Je nach Umfang und Fahrzeugzustand dauert eine komplette Fahrzeugaufbereitung in der Regel zwei bis drei Werktage, da wir in mehreren Stufen und in Handarbeit arbeiten." },
      { question: "Was gehört zu einer professionellen Fahrzeugaufbereitung?", answer: "Eine professionelle Fahrzeugaufbereitung umfasst die Außen- bzw. Lackaufbereitung (Vorwäsche, Handwäsche, Lackreinigung, Politur und Versiegelung) sowie die Innenraumaufbereitung (Staubsaugen, Polster- und Lederreinigung, Kunststoffpflege, Scheiben und Desinfektion)." },
      { question: "Lohnt sich eine Fahrzeugaufbereitung vor dem Verkauf?", answer: "Ja. Ein makelloser Zustand steigert den Verkaufspreis, sorgt für einen starken ersten Eindruck und minimiert bei einer Leasingrückgabe mögliche Nachberechnungen." },
      { question: "Was kostet eine Innenraumaufbereitung?", answer: "Eine reine Innenraumaufbereitung kostet weniger als eine komplette Aufbereitung. Der genaue Preis hängt vom Verschmutzungsgrad und der Fahrzeuggröße ab – ein verbindliches Angebot erhalten Sie nach kurzer Begutachtung." },
      { question: "Was ist der Unterschied zwischen einer Autowäsche und einer Fahrzeugaufbereitung?", answer: "Eine Autowäsche reinigt das Fahrzeug nur oberflächlich. Eine Fahrzeugaufbereitung reinigt, poliert, versiegelt und bereitet zusätzlich den Innenraum auf – das Ergebnis ist Werterhalt und langanhaltender Schutz statt kurzfristiger Sauberkeit." },
    ],
    contentBlocks: [
      { type: "p", text: "Bei einer professionellen Fahrzeugaufbereitung – auch Autoaufbereitung genannt – wird Ihr Fahrzeug innen und außen gründlich gereinigt, aufbereitet und geschützt: weit mehr als eine normale Autowäsche." },
      { type: "p", text: "Bei PB Fahrzeugpflege Saarlouis umfasst unser Premium-Detailing-Paket ein mehrstufiges, individuell abgestimmtes Programm aus Lack- und Innenraumaufbereitung und dauert je nach Umfang in der Regel zwei bis drei Werktage." },
      { type: "h2", text: "Lackaufbereitung" },
      { type: "p", text: "Perfekter Glanz und langanhaltender Schutz – für Fahrzeugliebhaber, die ihr Auto in perfektem Zustand genießen möchten:" },
      { type: "ul", items: [
        "Vorreinigung mit Hochdruck: Gründliche Entfernung von grobem Schmutz.",
        "Handwäsche von Profis: Schonende Reinigung, die jedes Detail berücksichtigt.",
        "Spezialreinigung: Embleme, Schriftzüge und Auspuffblenden werden akribisch gepflegt.",
        "Entfernung von Lackverunreinigungen: Beseitigung von Insekten, Teer, Flugrost und mehr.",
        "Felgenreinigung: Tiefenreinigung für strahlenden Glanz.",
        "Maschinelle & manuelle Lackreinigung: Entfernt tiefsitzenden Schmutz und Kratzer.",
        "Politur: Anti-Hologramm-Hochglanzpolitur für makellosen Glanz.",
        "Versiegelung: Auswahl aus Carnaubawachs, Nanoversiegelung oder 9H High-End Keramikversiegelung.",
      ]},
      { type: "h2", text: "Innenraumaufbereitung" },
      { type: "p", text: "Sauberkeit und Komfort auf höchstem Niveau – für Fahrzeugbesitzer, die das Beste aus ihrem Innenraum herausholen möchten:" },
      { type: "ul", items: [
        "Gründliche Staubsaugung: Erfasst auch schwer zugängliche Bereiche.",
        "Tiefenreinigung von Polstern und Teppichen: Entfernt tiefsitzenden Schmutz und Flecken.",
        "Lederpflege: Reinigung und Pflege für langanhaltenden Schutz und Geschmeidigkeit.",
        "Kunststoff- und Armaturenpflege: Sorgt für ein makelloses Finish.",
        "Scheibenreinigung: Für eine klare Sicht und strahlende Sauberkeit.",
        "Desinfektion & Geruchsbeseitigung: Frisches, hygienisches Innenraumklima.",
      ]},
      { type: "p", text: "Für Verkauf oder Leasingrückgabe optimieren wir gezielt den Fahrzeugzustand: Wertsteigerung durch makellosen Auftritt, bleibender erster Eindruck und Minimierung von möglichen Nachberechnungen. Je nach Zweck (Hochzeit, Fahrzeugverkauf, Leasingrückgabe, Werterhalt etc.) bieten wir verschiedene Detailing-Levels an. Gerne beraten wir Sie ausführlich in einem persönlichen Gespräch direkt bei uns vor Ort – ein Termin ist nicht erforderlich. Dauer: ca. 2–3 Werktage." },
      { type: "h2", text: "Was kostet eine Fahrzeugaufbereitung?" },
      { type: "p", text: "Die Kosten einer Fahrzeugaufbereitung hängen von Fahrzeuggröße, Zustand und gewünschtem Umfang ab – eine reine Innenraumaufbereitung kostet weniger als eine komplette Aufbereitung mit Lackpolitur und Versiegelung. Da wir jedes Fahrzeug individuell beurteilen, erstellen wir Ihnen nach einer kurzen Begutachtung ein transparentes Angebot, unverbindlich und ohne Termin. Eine Übersicht finden Sie auf unserer Seite Preise." },
      { type: "h2", text: "Fahrzeugaufbereitung im Saarland, in Saarlouis & Umgebung" },
      { type: "p", text: "Sie finden uns in der Provinzialstraße 243 in 66806 Ensdorf – direkt bei Saarlouis. Zu uns kommen Kunden aus dem gesamten Saarland, u. a. aus Saarlouis, Saarbrücken, Dillingen und St. Wendel, sowie aus Trier, Luxemburg und dem grenznahen Raum. Eine unverbindliche Begutachtung ist während der Öffnungszeiten auch ohne Termin möglich." },
      { type: "h2", text: "Autowäsche oder Fahrzeugaufbereitung – der Unterschied" },
      { type: "p", text: "Eine Autowäsche reinigt das Fahrzeug oberflächlich, eine Fahrzeugaufbereitung reinigt, bereitet auf und schützt Innenraum und Lack mehrstufig. Der Unterschied im Überblick:" },
      { type: "table",
        header: ["Kriterium", "Autowäsche", "Fahrzeugaufbereitung"],
        rows: [
          ["Umfang", "Schnelle Außenreinigung", "Mehrstufige Reinigung & Aufbereitung innen und außen"],
          ["Lack", "Nur oberflächlich sauber", "Reinigung, Politur und Versiegelung"],
          ["Innenraum", "Meist nicht enthalten", "Tiefenreinigung von Polstern, Leder, Desinfektion"],
          ["Dauer", "Wenige Minuten", "In der Regel 2–3 Werktage"],
          ["Ergebnis", "Sauberkeit auf Zeit", "Werterhalt & langanhaltender Schutz"],
        ]},
    ],
  },
  {
    slug: "lack-und-beulendoktor",
    faqs: [
      { question: "Was kostet Smart Repair?", answer: "Die Kosten richten sich nach Art, Größe und Lage des Schadens. Da nur die beschädigte Stelle bearbeitet wird, ist Smart Repair bis zu 70 % günstiger als eine herkömmliche Lackierung. Den genauen Preis nennen wir Ihnen nach einer kurzen Begutachtung – auch ohne Termin." },
      { question: "Kann man Dellen ohne Lackieren entfernen?", answer: "Ja. Kleinere Dellen und Beulen lassen sich mit der lackschadenfreien Ausbeultechnik entfernen, ohne den Originallack zu beschädigen – das ist schneller und günstiger als Spachteln und Lackieren." },
      { question: "Wie funktioniert die Ausbeultechnik beim Beulendoktor?", answer: "Bei der Ausbeultechnik wird die Delle mit speziellen Hebel- und Klebewerkzeugen vorsichtig zurück in die ursprüngliche Form gebracht. Der Lack bleibt dabei vollständig erhalten – auch bei modernen Materialien wie Aluminium." },
      { question: "Was ist der Unterschied zwischen Smart Repair und einer Lackierung?", answer: "Smart Repair repariert kleine Schäden punktuell und ist deutlich günstiger und schneller. Eine klassische Lackierung erneuert ganze Bauteile und ist aufwendiger. Für kleine Dellen und Lackschäden ist Smart Repair meist die bessere Wahl." },
      { question: "Wie lange dauert eine Beulenreparatur?", answer: "Eine Beulenreparatur dauert in der Regel etwa einen halben Werktag, eine Lackreparatur ca. drei Werktage – ideal vor einer Leasingrückgabe oder einem Fahrzeugverkauf." },
      { question: "Lohnt sich Smart Repair?", answer: "Ja. Smart Repair ist bis zu 70 % günstiger als eine Lackierung, schneller erledigt und verursacht durch die kleine Reparaturfläche weniger Wertminderung – Ihr Fahrzeug bleibt wertvoll." },
    ],
    contentBlocks: [
      { type: "p", text: "Beulendoktor & Smart Repair bei PB Fahrzeugpflege Saarlouis: Ihr Fahrzeug ist mehr als nur ein Transportmittel – es ist ein wertvolles Gut, das perfekte Pflege verdient. Unser Smart-Repair-Verfahren bietet Ihnen die ideale Lösung, um Lackschäden schnell, effektiv und kostengünstig zu beheben – in einer Qualität, die nur ein Premiumbetrieb wie unserer garantieren kann." },
      { type: "h2", text: "Smart Repair Saarland – Lackschäden günstig reparieren" },
      { type: "p", text: "Ihre Smart-Repair-Vorteile im Überblick:" },
      { type: "ul", items: [
        "Über 29 Jahre Erfahrung in der Reparatur von Beulen und Lackschäden.",
        "Ausgezeichnete Qualität: mehrfach für unseren erstklassigen Service und die herausragende Qualität ausgezeichnet.",
        "Hohe Kundenzufriedenheit: Weiterempfehlungsrate von über 95 %.",
        "Schnelle Reparaturzeit: Beulenreparatur ca. 0,5 Werktage, Lackreparaturen ca. 3 Werktage.",
        "Kostenersparnis: mit Smart Repair bis zu 70 % sparen gegenüber herkömmlichen Lackierungen.",
        "Umweltschonend: geringerer Materialverbrauch, nachhaltige Lackreparatur.",
        "Wertsteigerung: kleinere Reparaturflächen bedeuten weniger Wertminderung.",
      ]},
      { type: "p", text: "Unsere Philosophie: Qualität steht bei uns an erster Stelle. Wir setzen modernste Techniken ein, um sicherzustellen, dass die Reparatur den höchsten Standards entspricht – ohne Kompromisse. Sollten wir mit Smart Repair Grenzen erreichen, bieten wir dank unserer Zusammenarbeit mit den besten Kfz-Gutachtern, Karosseriebauern und Kfz-Lackierbetrieben auch umfangreichere Reparaturmethoden an. Ihr Vorteil: Alles aus einer Hand, alles in Premiumqualität. Sie brauchen sich um nichts zu kümmern." },
      { type: "h2", text: "Beulendoktor Saarland – Ausbeulen ohne Lackieren" },
      { type: "p", text: "Warum unnötig viel Geld für Spachteln und Lackieren ausgeben, wenn es auch einfacher geht? Wir setzen auf modernste Hebel- und Klebetechniken, die den Wert Ihres Fahrzeugs erhalten und perfekte Ergebnisse liefern." },
      { type: "ul", items: [
        "Lackschadenfreie Ausbeultechnik: entfernt Beulen und Dellen ohne den Lack zu beeinträchtigen.",
        "Über 29 Jahre Erfahrung mit Präzision und moderner Ausrüstung.",
        "Spezialisierung auf moderne Materialien: sicheres Arbeiten auch bei Aluminium und Thermoglas.",
        "Fachgerechte Reparaturen, die verhindern, dass aus kleinen Beulen große Probleme werden.",
        "187 positive Bewertungen: zufriedene Kunden sprechen für sich.",
      ]},
      { type: "p", text: "Vermeiden Sie unnötige Schäden durch unprofessionelle Beulen-Reparaturen und kommen Sie direkt zu den Experten. Wir bieten Ihnen eine unverbindliche Begutachtung Ihres Schadens – jederzeit und ohne Termin." },
      { type: "h2", text: "Was kostet Smart Repair?" },
      { type: "p", text: "Die Kosten für Smart Repair hängen von Art, Größe und Lage des Schadens ab. Da nur die beschädigte Stelle bearbeitet wird, ist Smart Repair bis zu 70 % günstiger als eine herkömmliche Lackierung des gesamten Bauteils. Den genauen Preis nennen wir Ihnen nach einer kurzen, unverbindlichen Begutachtung – auch ohne Termin. Eine Übersicht finden Sie auf unserer Seite Preise." },
      { type: "h2", text: "Wie funktioniert die Ausbeultechnik? Dellen ohne Lackieren" },
      { type: "p", text: "Ja – kleinere Dellen und Beulen lassen sich ohne Lackieren entfernen. Bei der lackschadenfreien Ausbeultechnik (auch Paintless Dent Repair) wird die Delle mit speziellen Hebel- und Klebewerkzeugen vorsichtig von hinten oder außen zurück in ihre ursprüngliche Form gebracht – der Originallack bleibt dabei vollständig erhalten. Das ist schneller und günstiger als Spachteln und Lackieren und vermeidet eine Wertminderung durch nachlackierte Teile." },
      { type: "h2", text: "Smart Repair oder klassische Lackierung – der Unterschied" },
      { type: "p", text: "Smart Repair repariert kleine Schäden punktuell und günstig, eine klassische Lackierung erneuert ganze Bauteile. Der Unterschied im Überblick:" },
      { type: "table",
        header: ["Merkmal", "Smart Repair", "Klassische Lackierung"],
        rows: [
          ["Kosten", "Bis zu 70 % günstiger", "Höher – ganzes Bauteil"],
          ["Umfang", "Punktuelle Reparatur kleiner Schäden", "Lackierung kompletter Bauteile"],
          ["Dauer", "Beule ca. 0,5 · Lack ca. 3 Werktage", "Meist länger"],
          ["Wertminderung", "Gering – kleine Reparaturfläche", "Höher, ggf. dokumentationspflichtig"],
          ["Ideal für", "Parkdellen, kleine Lack- & Karosserieschäden", "Großflächige oder tiefe Schäden"],
        ]},
      { type: "p", text: "Bei größeren oder tiefen Schäden – etwa nach einem Unfall – bieten wir dank unserer Zusammenarbeit mit Gutachtern, Karosseriebauern und Lackierbetrieben auch umfangreichere Reparaturen an: alles aus einer Hand." },
      { type: "h2", text: "Typische Schäden: Parkdellen, Steinschläge & mehr" },
      { type: "p", text: "Mit Smart Repair und unserer Ausbeultechnik beheben wir unter anderem Parkdellen, Türkantendellen, kleinere Beulen, Steinschläge und kleine Lackkratzer. So bleibt Ihr Fahrzeug optisch und im Wert erhalten – ohne aufwendige Komplettlackierung." },
      { type: "h2", text: "Smart Repair & Beulendoktor im Saarland" },
      { type: "p", text: "Sie finden uns in der Provinzialstraße 243 in 66806 Ensdorf – direkt bei Saarlouis. Als Lack- und Beulendoktor sind wir für Kunden aus dem gesamten Saarland da, u. a. aus Saarlouis, Saarbrücken, Dillingen und St. Wendel, sowie aus Luxemburg und dem grenznahen Raum. Eine unverbindliche Begutachtung Ihres Schadens ist während der Öffnungszeiten auch ohne Termin möglich." },
    ],
  },
];
